title: Speculative Cosmologies 
baseurl: "/designing-for-greater-evil/" # the subpath of your site, e.g. /blog
url: "https://sitraka-.github.io"

# Build settings
markdown: kramdown
# theme: minima
# remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-feed
# - jekyll-remote-theme # add this line to the plugins list if you already have one